# Generated by Django 3.1 on 2020-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200902_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ManyToManyField(blank=True, to='products.Provider'),
        ),
    ]
