# Generated by Django 3.1 on 2020-09-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EUR Order Total')),
                ('emailAddress', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingName', models.CharField(blank=True, max_length=254)),
                ('billingAddress1', models.CharField(blank=True, max_length=254)),
                ('billingCity', models.CharField(blank=True, max_length=254)),
                ('billingPostcode', models.CharField(blank=True, max_length=254)),
                ('billingCountry', models.CharField(blank=True, max_length=254)),
                ('ShippingName', models.CharField(blank=True, max_length=254)),
                ('ShippingAddress1', models.CharField(blank=True, max_length=254)),
                ('ShippingCity', models.CharField(blank=True, max_length=254)),
                ('ShippingPostcode', models.CharField(blank=True, max_length=254)),
                ('ShippingCountry', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EUR price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
