# Generated by Django 3.1 on 2020-09-21 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
