# Generated by Django 3.1 on 2020-10-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_caropics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caropics',
            name='Caropic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
