# Generated by Django 3.1 on 2020-10-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201016_1153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caropics',
            table='CaroPics',
        ),
    ]
