# Generated by Django 3.1 on 2020-10-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201016_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caropics',
            options={'verbose_name_plural': 'Caro Pics'},
        ),
        migrations.AlterModelTable(
            name='caropics',
            table=None,
        ),
    ]
