# Generated by Django 3.1 on 2020-10-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201016_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caropics',
            name='Caropic',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
