# Generated by Django 3.1 on 2020-10-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201016_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caropics',
            name='Caropic',
            field=models.ImageField(blank=True, upload_to='CaroPics'),
        ),
    ]
