# Generated by Django 3.1 on 2020-10-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201016_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caropics',
            old_name='Caropic',
            new_name='image',
        ),
    ]
