# Generated by Django 3.1 on 2020-10-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201016_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caropics',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
