# Generated by Django 3.1 on 2020-10-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20201016_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactorer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.manufactorer'),
        ),
    ]
