# Generated by Django 3.1 on 2020-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20201019_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caropics',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
