# Generated by Django 3.1 on 2020-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20201019_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/mobile-2468068_1920.png', null=True, upload_to='product'),
        ),
    ]
