# Generated by Django 3.1 on 2020-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20201020_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/mobile-2468068_1920.png', null=True, upload_to='product'),
        ),
    ]
