# Generated by Django 3.1 on 2020-11-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20201020_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/mobile-2468068_1920.png', null=True, upload_to='product'),
        ),
    ]
