# Generated by Django 3.1 on 2020-11-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201103_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/mobile-2468068_1920.png', null=True, upload_to='product'),
        ),
    ]
