# Generated by Django 3.1 on 2020-11-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20201104_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/mobile-2468068_1920.png', upload_to='product'),
        ),
    ]
