# Generated by Django 3.1 on 2020-11-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20201104_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactorer',
            field=models.ForeignKey(help_text='if missing, you can add the maufactoer on the dedicated form on this page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.manufactorer'),
        ),
    ]
