# Generated by Django 3.1 on 2020-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20201104_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/mobile-2468068_1920.png', upload_to='product'),
        ),
    ]
